ExLlamaV2 Mistral, Memory support, qualitative comparision and improvements
premAI-io/benchmarks pull request #177
Opened 2024-04-22 07:20 UTC by Anindyadeep

This PR introduces all the changes by PR https://github.com/premAI-io/benchmarks/pull/167 and integrates those in Optimum Nvidia. Optimum Nvidia README now has quality checks table for both Llama 2 Chat and Mistral Instruct.

Note this PR depends on: #175

2024-04-23 15:54 UTC, nsosio requested changes
minor things related to exllaamv2

2024-04-23 15:54 UTC, nsosio commented on bench_exllamav2/bench.sh
wrong file?

2024-04-24 07:37 UTC, Anindyadeep commented on bench_exllamav2/bench.sh
Yes, sorry it was by mistake, fixed it

2024-04-24 07:38 UTC, Anindyadeep commented on docs/llama2.md.template
> +| [exllamav2](/bench_exllamav2/)              |      -       |      -         | 125.58 ± 1.23 | 159.68 ± 1.85 |
I just merged the changes with dev and now it should hopefully be fine

2024-04-24 09:16 UTC, nsosio approved these changes
LGTM

2024-04-24 09:16 UTC, merged